@startuml inventory-product-receive
|u|User
|s|System

|u|
start
:(1) Click "Products Receive Nav Btn";

|s|
:(2) Load "Receive Products" screen;

|u|
:(3) Select Production Order;

|s|
:(4) Load "Receive Products Details" screen;

|u|
:(5) Check information;

if (Ok?) then (no)
    |u|
    :(5.1.1) Click "Products Return Btn";

    |s|
    :(5.1.2) Load "Return" dialog;

    |u|
    :(5.1.3) Enter problem info\nand click "Return Ok Btn";
else (yes)
    |u|
    :(5.2) Click "Products Receive Btn";
endif

|s|
:(6) Update status of Production Order;
:(7) Update stock;
:(8) Notify relevant users;
stop
@enduml