@startuml inventory-supply-receive
|u|User
|s|System

|u|
start
:(1) Click "Supplies Receive Nav Btn";

|s|
:(2) Load "Select Purchase Order" screen;

|u|
:(3) Select Purchase Order;

|s|
:(4) Load "Receive Purchased Supplies" screen;

|u|
:(5) Check information;

if (Ok?) then (no)
    |u|
    :(5.1.1) Click "Supplies Return Btn";

    |s|
    :(5.1.2) Load "Report problem" dialog;

    |u|
    :(5.1.3) Enter problem info\nand click "Report Ok Btn";
else (yes)
    |u|
    :(5.2) Click "Supplies Receive Btn";
endif

|s|
:(6) Update status of Purchase Order;
:(7) Update stock;
:(8) Update status of associated\nPurchase Requisition;
:(9) Notify relevant users;
stop
@enduml