@startuml production-generate-report
|u|User
|s|System

|u|
start
:(1) Click "Production Report";

|s|
:(2) Load corresponding screen;

|u|
:(3) Select time range;
:(4) Click "Generate";

|s|
:(5) Generate Production report;
stop
@enduml