@startuml production-order-update-progress
|u|User
|s|System

|u|
start
repeat
    if (Clicked?) then (PDO Progress Add Btn)
        |s|
        :(1.1.1) Load "Add\nProgress Update" dialog;
        |u|
        :(1.1.2) Enter info and click\n"Progress Add Ok Btn";
    else (PDO Progress Edit Btn\non a progress item)
        |s|
        :(1.2.1) Switch item\nto edit mode;
        |u|
        :(1.2.2) Enter info and click\n"Progress Edit Ok Btn";
    endif
    |s|
    :(2) Validate entered info;
    backward: (2.1) Show validation\nerror messages;
repeat while (Valid?) is (no)
->yes;
:(2.2) Save progress updates;
stop
@enduml