@startuml production-order-view
|u|User
|s|System

|u|
start
:(1) Click "PDO Nav Btn";

|s|
:(2) Load "Production Orders" screen;

|u|
:(3) Set search and filters;

|s|
:(4) Load search and filter result;

|u|
:(5) Select item;

|s|
:(6) Load "Production Order Details" screen;
stop
@enduml