@startuml production-order-create
|u|User
|s|System

|u|
start
:(1) Click "PDO Create Btn";

|s|
:(2) Load "Create Production Order" screen;

|u|
repeat
    :(3) Enter info and click "PDO Create Ok Btn";
    |s|
    :(4) Validate entered info;
    backward: (4.1.1) Show validation\nerror messages;
repeat while (Valid?) is (no)
->yes;
:(4.2.1) Save item;
:(4.2.2) Notify relevant users;
stop
@enduml