@startuml production-order-update
|u|User
|s|System

|u|
start
repeat
    :(1) Edit data;
    :(2) Click "Save";

    |s|
    :(3) Validate entered data;
    backward:(3.1) Show validation
    error messages;
repeat while (Valid?) is (no)
->yes;
:(3.2) Save updated Production Order;
:(4) Notify Director and Production manager;
stop
@enduml