@startuml purchase-requisition-update
|u|User
|s|System

|u|
start
repeat
    :(1) Edit info and click\n"Update" or "Cancel";
    |s|
    :(2) Validate entered info;
    backward: (2.1.1) Show validation\nerror messages;
repeat while (Valid?) is (no)
->yes;
:(2.2.1) Save item;
:(2.2.2) Notify relevant users;
stop
@enduml