@startuml purchase-requisition-create
|u|User
|s|System

|u|
start
:(1) Click "PR Create Btn";

|s|
:(2) Load "Create Purchase Requisition" screen;

|u|
repeat
    :(3) Enter info and click "PR Create Ok Btn";
    |s|
    :(4) Validate entered info;
    backward: (4.1.1) Show validation\nerror messages;
repeat while (Valid?) is (no)
->yes;
:(4.2.1) Save item;
:(4.2.2) Notify relevant users;
stop
@enduml