@startuml purchase-order-complete-payment
|u|User
|s|System

|u|
start
:(1) Click "PO Complete Payment Btn";

|s|
:(2) Load "Receipt Upload" dialog;

|u|
:(3) Enter pay amount,\nupload receipt receipt, and click\n"PO Complete Payment Ok Btn";

|s|
:(4) Save receipt and payment;
:(5) Notify relevant users;
stop
@enduml