@startuml purchase-requisition-view
|u|User
|s|System

|u|
start
:(1) Click "PR Nav Btn";

|s|
:(2) Load "Purchase Requisitions" screen;

|u|
:(3) Set search and filters;

|s|
:(4) Load search and filter result;

|u|
:(5) Select item;

|s|
:(6) Load "Purchase Requisition Details" screen;
stop
@enduml