@startuml purchase-order-update-progress
|u|User
|s|System

|u|
start
repeat
    :(1) Add/Edit/Delete status updates;
    :(2) Click "Save";

    |s|
    :(3) Validate entered data;
    backward:(3.1) Show validation
    error messages;
repeat while (Valid?) is (no)
->yes;
:(3.2) Save status updates;
:(4) Update status of associated\nPurchase Requisition;
stop
@enduml