@startuml purchase-requisition-update
|u|User
|s|System

|u|
start
repeat
    :(1) Edit info and click\n"PR Update Btn" or "PR Cancel Btn";
    |s|
    if ("Cancel?") then (yes)
        :(1.1.1) Load "Cancel" dialog;
        |u|
        :(1.1.2) Enter problem info\nand click "Cancel Ok Btn";
    else (no)
    endif
    |s|
    :(2) Validate entered info;
    backward: (2.1.1) Show validation\nerror messages;
repeat while (Valid?) is (no)
->yes;
:(2.2.1) Save item;
:(2.2.2) Notify relevant users;
stop
@enduml