@startuml purchase-order-update
|u|User
|s|System

|u|
start
repeat
    :(1) Edit info and click "Save";
    |s|
    :(2) Validate entered info;
    backward: (2.1) Show validation error messages;
repeat while (Valid?) is (no)
->yes;
:(2.2) Save item;
stop
@enduml