@startuml purchase-requisition-approve
|u|User
|s|System

|u|
start
:(1) Click "PR Approve Btn" or "PR Reject Btn";
if (Click) then (Approve)
    |s|
    :(1.1.1) Load "Approve Purchase\nRequisition" dialog;
    |u|
    :(1.1.2) Click "PR Approve Ok Btn";
else (Reject)
    |s|
    :(1.2.1) Load "Reject Purchase\nRequisition" dialog;
    |u|
    :(1.2.2) Enter problem info\nand click "PR Reject Ok Btn";
endif
|s|
:(2) Save item;
:(3) Notify relevant users;
stop
@enduml