@startuml purchase-requisition-approve
|u|User
|s|System

|u|
start
:(1) Click "Approve" or "Reject";
if (Click) then (Approve)
    |s|
    :(1.1) Approve item;
else (Reject)
    |s|
    :(1.2) Reject item;
endif

:(2) Notify relevant users;
stop
@enduml