@startuml report-generate
|u|User
|s|System

|u|
start
:(1) Click "Reports Nav Btn";

|s|
:(2) Load "Reports" screen;

|u|
:(3) Select report type and time range\nthen click "Report Generate Btn";

|s|
:(4) Generate report;
stop
@enduml