@startuml retailer-manage
|u|User
|s|System

|u|
start
:(1) Click "Retailers Nav Btn";

|s|
:(2) Load "Retailers" screen;

|u|
:(3) Set search\nand filters;

|s|
:(4) Load search\nand filter result;

|u|
:(5) Click "Retailer Add Btn"\nor select an item;

if (Item selected?) then (yes)
|s|
:(5.1) Load "Retailer Details"\nscreen;
else (no)
:(5.2) Load "Add Retailer"\nscreen;
endif

|u|
repeat
    :(6) Enter info and click\n"Retailer Save Btn";

    |s|
    :(7) Validate entered info;
    backward: (7.1) Show validation\nerror messages;
repeat while (Valid?) is (no)
->yes;
:(7.2) Save item;
stop
@enduml