@startuml sales-order-update-progress
|u|User
|s|System

|u|
start
repeat
    :(1) Enter info and\nclick "SO Progress Add Ok Btn"\nor "SO Progress Edit Ok Btn";
    |s|
    :(2) Validate entered info;
    backward: (2.1) Show validation error messages;
repeat while (Valid?) is (no)
->yes;
:(2.2) Save progress updates;
stop
@enduml