@startuml sales-order-complete
|u|User
|s|System

|u|
start
if (Return order?) then (yes)
    |u|
    :(1.1.1) Click "SO\nReturn Btn";

    |s|
    :(1.1.2) Load "Return" dialog;

    |u|
    :(1.1.3) Enter problem info\nand click "Return Ok Btn";

    |s|
    :(1.1.4) Return order;
else (no)
    |u|
    :(1.2.1) Click "SO\nComplete Btn";

    |s|
    :(1.2.2) Complete order;
    :(1.2.3) Generate and\nsend invoice to retailer;
endif
stop
@enduml