@startuml user-deactivate
|u|User
|s|System

|u|
start
:(1) Click "Deactivate";

|s|
:(2) Display confirmation dialog;

|u|
:(3) Confirm;
|s|
if (Confirm?) then (yes)
    :(3.1) Deactivate user;
else (no)
endif
stop
@enduml