@startuml inventory-supply-issue
autonumber

actor "Production\nPlanner" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Click "Start"
f -> b : Start order
activate b
return Start succeeds
f --> a : Start succeeds
deactivate f
@enduml