@startuml inventory-product-receive
autonumber

actor "Inventory Specialist" as a
participant UI as f
participant System as b

a -> f : Click "Products\nReceive Nav Btn"
activate f
f -> b : GetProductionOrders()
activate b
return ProductionOrderDto[]
f --> a : ProductionOrderDto[]
a -> f : Select item
f -> f : LoadScreen\n("Receive Products Details")
f -> b : GetProductionOrder(id)
activate b
return ProductionOrderDto
f --> a : ProductionOrderDto
a -> f : Click buttons

alt Clicked = "Products Receive Btn"
    f -> b : ReceiveProducts\n(productionOrderId)
    activate b
    b -> b : UpdateStock()
    b -> b : NotifyComplete()
    return SuccessMsg
    f --> a : SuccessMsg
else Clicked = "Products Return Btn"
    f -> f : LoadDialog("Return")
    a -> f : Enter problem\nthen click "Return Ok Btn"
    f -> b : ReturnProducts\n(productionOrderId, input)
    activate b
    b -> b : NotifyReturn()
    return SuccessMsg
    f --> a : SuccessMsg
end
@enduml