@startuml inventory-product-receive
autonumber

actor "Inventory Specialist" as a
participant UI as f
participant System as b

a -> f : Click "Receive Products"
activate f
f -> b : GetProductionOrders()
activate b
return ProductionOrderDto[]
f --> a : ProductionOrderDto[]
a -> f : Select item
f -> b : GetProductionOrder(id)
activate b
return ProductionOrderDto
f --> a : ProductionOrderDto
a -> f : Click "Receive"\nor "Report Problem"

alt Receive
    f -> b : ReceiveProducts(productionOrderId)
    activate b
    b -> b : CompleteProductionOrder(id)
    b -> b : UpdateStock(newStock)
    b -> b : Notify()
    return SuccessMsg
    f --> a : SuccessMsg
else Report Problem
    f -> f : LoadReportProblemDialog()
    a -> f : Enter problem\nthen click "Report"
    f -> b : ReturnProducts(productionOrderId, input)
    activate b
    b -> b : Notify()
    return SuccessMsg
    f --> a : SuccessMsg
    deactivate f
end
@enduml