@startuml inventory-product-issue
autonumber

actor "Inventory Specialist" as a
participant UI as f
participant Backend as b

a -> f : Click "Issue Products"
activate f
f -> b : GetAll()
activate b
return SalesOrderDto[]
f --> a : SalesOrderDto[]
a -> f : Select item
f -> b : Get(id)
activate b
return SalesOrderDto
f --> a : SalesOrderDto
a -> f : Click "Issue"
f -> b : IssueProducts(salesOrderId)
activate b
return SuccessMessage
return SuccessMessage
@enduml