@startuml inventory-supply-issue
autonumber

actor "Inventory Specialist" as a
participant UI as f
participant Backend as b

a -> f : Click "Issue Supplies"
activate f
f -> b : GetAll()
activate b
return ProductionOrderDto[]
f --> a : ProductionOrderDto[]
a -> f : Select item
f -> b : Get(id)
activate b
return ProductionOrderDto
f --> a : ProductionOrderDto
a -> f : Click "Issue"
f -> b : IssueSupplies(productionOrderId)
activate b
return SuccessMessage
return SuccessMessage
@enduml