@startuml inventory-supply-receive
autonumber

actor "Inventory Specialist" as a
participant UI as f
participant System as b

a -> f : Click "Supplies\nReceive Nav Btn"
activate f
f -> b : GetPurchaseOrders()
activate b
return PurchaseOrderDto[]
f --> a : PurchaseOrderDto[]
a -> f : Select item
f -> f : LoadScreen\n("Receive Supplies Details")
f -> b : GetPurchaseOrder(id)
activate b
return PurchaseOrderDto
f --> a : PurchaseOrderDto
a -> f : Click buttons

alt Clicked = "Supplies Receive Btn"
    f -> b : ReceiveSupplies\n(purchaseOrderId)
    activate b
    b -> b : UpdateStock()
    b -> b : NotifyComplete()
    return SuccessMsg
    f --> a : SuccessMsg
else Clicked = "Supplies Return Btn"
    f -> f : LoadDialog("Return")
    a -> f : Enter problem then\nclick "Return Ok Btn"
    f -> b : ReturnSupplies\n(purchaseOrderId, input)
    activate b
    b -> b : NotifyReturn()
    return SuccessMsg
    f --> a : SuccessMsg
end
@enduml