@startuml inventory-generate-report
autonumber

actor "Inventory\nManager" as a
participant Screen as f
participant Backend as b

a -> f : Click "Inventory Report"
activate f
a -> f : Select time range
f -> b : Generate report
activate b
return Report
return Report
@enduml