@startuml my-account-login
autonumber

actor "User" as a
participant UI as f
participant Backend as b

a -> f : Click "Login"
activate f
a -> f : Login credentials
f -> b : Login(loginDto)
activate b

alt authentication succeeds
    b --> f : User
    f --> a : SuccessMsg
    f -> f : DisplayHomeScreen()
else authentication fails
    return AuthFailureMsg
    f --> a : AuthFailureMsg
    deactivate f
end
@enduml