@startuml my-account-manage
autonumber

actor "User" as a
participant Screen as f
participant Backend as b

a -> f : Click "My account"
activate f
f -> b : Get account info
activate b
return Account info
f --> a : Account info
a -> f : Enter data and\nClick "Save"
f -> b : Update account info
activate b
b -> b : Validate info

alt validation succeeds
    b -> b : Update account info
    b --> f : Updated account info
    f --> a : Updated account info
else validation fails
    return Validation failures
    f --> a : Validation failures
    deactivate f
end
@enduml