@startuml my-account-login
autonumber

actor "User" as a
participant UI as f
participant System as b

activate f
a -> f : Enter login credentials\nand click "Login Btn"
f -> b : Login(input)
activate b

alt succeeds
    b --> f : UserDto
    f --> a : "Login succeeds"
    f -> f : LoadScreen("Home")
else  fails
    return AuthFailure
    f --> a : AuthFailure
    deactivate f
end
@enduml