@startuml my-account-login
autonumber

actor "User" as a
participant Screen as f
participant Backend as b

a -> f : Click "Login"
activate f
a -> f : Enter login credential and\nClick "Save"
f -> b : Authenticate
activate b

alt authentication succeeds
    b --> f : User info
    f --> a : Login succeeds
    f -> f : Load homepage screen
else authentication fails
    return Authentication failure
    f --> a : Authentication failure
    deactivate f
end
@enduml