@startuml my-account-logout
autonumber

actor "User" as a
participant UI as f
participant System as b

activate f
a -> f : Click "Logout"
f -> b : Logout()
activate b
return SuccessMsg
f --> a : SuccessMsg
f -> f : DisplayLoginScreen()
@enduml