@startuml my-notification-view
autonumber

actor "User" as a
participant UI as f
participant System as b

activate f
a -> f : Click "Notifications\nNav Btn"
f -> b : GetNotifications()
activate b
return NotificationDto[]
f --> a : NotificationDto[]

a -> f : Read notifications
f -> b : MarkNoticesAsRead(ids)
activate b
@enduml