@startuml my-notification-view
autonumber

actor "User" as a
participant UI as f
participant System as b

activate f
a -> f : Click "Notifications"
f -> b : GetNotifications()
activate b
return Notification[]
f --> a : Notification[]

a -> f : Read notifications
f -> b : MarkNoticesAsRead(ids)
activate b
@enduml