@startuml production-order-update
autonumber

actor "Production Planner" as a
participant UI as f
participant System as b
participant Database as d

activate f

alt Update
    a -> f : Edit info and\nclick "PDO Update Btn"
else Cancel
    a -> f : Click "PDO Cancel Btn"
    f -> f : LoadDialog("Cancel")
    a -> f : Enter problem and\nclick "Cancel Ok Btn"
end

f -> b : UpdateProductionOrder\n(id, input)
activate b
b -> b : Validate(input)

alt validation succeeds
    b -> d : Update\n("ProductionOrders", item)
    activate d
    return ProductionOrder
    b -> b : Notify()
    b --> f : ProductionOrderDto
    f --> a : ProductionOrderDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
end
@enduml