@startuml production-order-create
autonumber

actor "Production Planner" as a
participant UI as f
participant System as b

a -> f : Click "PDO Create Btn"
activate f
a -> f : Enter info and click\n"PDO Create Ok Btn"
f -> b : CreateProductionOrder\n(input)
activate b
b -> b : Validate(input)

alt validation succeeds
    b -> b : Notify()
    b --> f : ProductionOrderDto
    f -> f : LoadScreen\n("Production Order Details")
    f --> a : ProductionOrderDto
else validation fails
    return ValidationFailure
    return ValidationFailure
end
@enduml