@startuml production-order-approve
autonumber

actor "Production Manager" as a
participant UI as f
participant System as b

activate f
a -> f : Click "PDO Approve Btn"\nor "PDO Reject Btn"

alt Clicked = "PDO Approve Btn"
    f -> f : LoadDialog("Approve")
    a -> f : Click "Approve Ok Btn"
    f -> b : ApproveProductionOrder\n(id)
    activate b
    b -> b : NotifyApproval()
    b --> f : SuccessMsg
    deactivate b
    f --> a : SuccessMsg
else Clicked = "PDO Reject Btn"
    f -> f : LoadDialog("Reject")
    a -> f : Enter problem info and\nclick "Reject Ok Btn"
    f -> b : RejectProductionOrder\n(id, input)
    activate b
    b -> b : NotifyRejection()
    return SuccessMsg
    f --> a : SuccessMsg
    deactivate f
end
@enduml