@startuml production-order-view
autonumber

actor "Production Specialist" as a
participant UI as f
participant System as b
participant Database as d

a -> f : Click "Production\nOrders Nav Btn"
activate f
f -> b : GetProductionOrders()
activate b
b -> d : GetMany\n("ProductionOrders", query)
activate d
return ProductionOrder[]
return ProductionOrderDto[]
f --> a : ProductionOrderDto[]
a -> f : Set search and filters
f -> b : GetProductionOrders\n(searchOpts)
activate b
return ProductionOrderDto[]
f --> a : ProductionOrderDto[]
a -> f : Select item
f -> f : LoadScreen\n("Production Order Details")
f -> b : GetProductionOrder(id)
activate b
b -> d : Get\n("ProductionOrders", id)
activate d
return ProductionOrder
return ProductionOrderDto
f --> a : ProductionOrderDto
@enduml