@startuml purchase-requisition-approve
autonumber

actor "Finance\nProduction Manager" as a
participant UI as f
participant Backend as b

activate f
a -> f : Click "Approve" or "Reject"

alt Approve
    f -> b : ApprovePurchaseRequisition(id)
    activate b
    b --> f : SuccessMessage
    deactivate b
    f --> a : SuccessMessage
else Reject
    f -> b : RejectPurchaseRequisition(id)
    activate b
    return SuccessMessage
    f --> a : SuccessMessage
    deactivate f
end
@enduml