@startuml purchase-requisition-create
autonumber

actor "Production\nplanner" as a
participant Screen as f
participant Backend as b

a -> f : Click "Create"
activate f
f --> a : Screen
a -> f : Enter data and\nClick "Save"
f -> b : Create item
activate b
b -> b : Validate item

alt validation succeeds
    b -> b : Create item
    b -> b : Notify Production manager\nand Finance for Approval
    b --> f : New item
    f --> a : New item
else validation fails
    return Validation failures
    return Validation failures
end
@enduml