@startuml purchase-order-view
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant Backend as b

a -> f : Click "Purchase Orders"
activate f
f -> b : GetAll()
activate b
return PurchaseOrderDto[]
f --> a : PurchaseOrderDto[]
a -> f : Set search and filters
f -> b : GetAll(SearchFilterOpts)
activate b
return PurchaseOrderDto[]
f --> a : PurchaseOrderDto[]
a -> f : Select item
f -> b : Get(id)
activate b
return PurchaseOrderDto
return PurchaseOrderDto
@enduml