@startuml purchase-order-update-status
autonumber

actor "Procurement\nSpecialist" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Add/Edit/Delete status updates\nand Click "Save"
f -> b : Add/Edit/Delete\nstatus updates
activate b
b -> b : Validate status updates

alt validation succeeds
    b -> b : Update associated\nPurchase Requisition
    b --> f : New/Edited\nstatus updates
    f --> a : New/Edited\nstatus updates
else validation fails
    return Validation failures
    f --> a : Validation failures
    deactivate f
end
@enduml