@startuml purchase-order-update
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant System as b

activate f
a -> f : Edit info and\nclick "Save"
f -> b : UpdatePurchaseOrder(id, input)
activate b
b -> b : Validate(input)

alt validation succeeds
    b -> b : UpdatePurchaseRequisitionStatus()
    b -> b : Notify()
    b --> f : PurchaseOrderDto
    f --> a : PurchaseOrderDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
    deactivate f
end
@enduml