@startuml purchase-requisition-create
autonumber

actor "Production\nPlanner" as a
participant UI as f
participant Backend as b

a -> f : Click "Create"
activate f
a -> f : Enter info and\nclick "Save"
f -> b : CreatePurchaseRequisition(createDto)
activate b
b -> b : Validate(createDto)

alt validation succeeds
    b -> b : Notify()
    b --> f : PurchaseRequisitionDto
    f --> a : PurchaseRequisitionDto
else validation fails
    return ValidationFailure
    return ValidationFailure
end
@enduml