@startuml purchase-order-update-progress
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant System as b

activate f
a -> f : Add/Edit progress updates
f -> b : Add/UpdatePurchaseOrderEvent(orderId, inputDto)
activate b
b -> b : Validate(inputDto)

alt validation succeeds
    b --> f : EventDto[]
    f --> a : EventDto[]
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
    deactivate f
end
@enduml