@startuml purchase-requisition-view
autonumber

actor "Production\nPlanner" as a
participant UI as f
participant Backend as b

a -> f : Click "Purchase Requisitions"
activate f
f -> b : GetAll()
activate b
return PurchaseRequisitionDto[]
f --> a : PurchaseRequisitionDto[]
a -> f : Set search and filters
f -> b : GetAll(SearchFilterOpts)
activate b
return PurchaseRequisitionDto[]
f --> a : PurchaseRequisitionDto[]
a -> f : Select item
f -> b : Get(id)
activate b
return PurchaseRequisitionDto
return PurchaseRequisitionDto
@enduml