@startuml purchase-order-create
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant Backend as b

activate f
a -> f : Click "Create\nPurchase Order"
f -> f : GenerateOrderPreview()
a -> f : Edit info and\nclick "Create"
f -> b : CreatePurchaseOrder(createDto)
activate b
b -> b : Validate(createDto)

alt validation succeeds
    b -> b : StartPurchaseRequisitionFulfillment(id)
    b --> f : PurchaseRequisitionDto
    f --> a : PurchaseRequisitionDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
    deactivate f
end
@enduml