@startuml purchase-requisition-cancel
autonumber

actor "Production\nplanner" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Click "Cancel"
f -> b : Cancel item
activate b
b -> b : Cancel item
return Cancel succeeds
f --> a : Cancel succeeds
deactivate f
@enduml