@startuml purchase-order-complete-payment
autonumber

actor "Finance" as a
participant UI as f
participant System as b

a -> f : Click "Complete payment"
activate f
f -> f : OpenCompletePaymentDialog()
a -> f : Receipt PDF
f -> b : CompletePurchasePayment(orderId, input)
activate b
b -> b : Notify()
return SuccessMsg
return SuccessMsg
@enduml