@startuml purchase-requisition-update
autonumber

actor "Production\nplanner" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Enter data and\nClick "Save"
f -> b : Update item
activate b
b -> b : Validate item

alt validation succeeds
    b -> b : Notify Production manager\nand Finance for Approval
    b --> f : Updated item
    f --> a : Updated item
else validation fails
    return Validation failures
    f --> a : Validation failures
    deactivate f
end
@enduml