@startuml purchase-order-update
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant Backend as b

activate f
a -> f : Edit info and\nclick "Save"
f -> b : UpdatePurchaseOrder(updateDto)
activate b
b -> b : Validate(updateDto)

alt validation succeeds
    b --> f : PurchaseOrderDto
    f --> a : PurchaseOrderDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
    deactivate f
end
@enduml