@startuml purchase-order-create
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant System as b
participant Database as d

activate f
a -> f : Click "PO Create Btn"
f -> f : LoadScreen\n("Create Purchase Order")
a -> f : Edit info and click\n"PO Create Ok Btn"
f -> b : CreatePurchaseOrder\n(input)
activate b
b -> b : Validate(input)

alt validation succeeds
    b -> d : Insert\n("PurchaseOrders", item)
    activate d
    return PurchaseOrder
    b --> f : PurchaseOrderDto
    f -> f : LoadScreen\n("Purchase Order Details")
    f --> a : PurchaseOrderDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
    deactivate f
end
@enduml