@startuml purchase-order-update-status
autonumber

actor "Procurement\nspecialist" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Add/Edit/Delete status updates\nand Click "Save"
f -> b : Status updates to\ncreate/edit/delete
activate b
b -> b : Validate Status updates

alt validation succeeds
    b --> f : New/Edited\nStatus updates
    f --> a : New/Edited\nStatus updates
else validation fails
    return Validation failures
    f --> a : Validation failures
    deactivate f
end
@enduml