@startuml purchase-order-create
autonumber

actor "Finance" as a
participant Screen as f
participant Backend as b

a -> f : Click "Generate\nPurchase Order"
activate f
f --> a : Screen with\nPurchase Order info
a -> f : Click "Generate"
f -> b : Generate item
activate b
b -> b : Generate item
return New item
return New item
@enduml