@startuml purchase-requisition-update
autonumber

actor "Production Planner" as a
participant UI as f
participant System as b

activate f

alt Update
    a -> f : Edit info and\nclick "PR Update Btn"
else Cancel
    a -> f : Click "PR Cancel Btn"
    f -> f : LoadDialog("Cancel")
    a -> f : Enter problem and\nclick "Cancel Ok Btn"
end

f -> b : UpdatePurchaseRequisition\n(id, input)
activate b
b -> b : Validate(input)

alt validation succeeds
    b -> b : Notify()
    b --> f : PurchaseRequisitionDto
    f --> a : PurchaseRequisitionDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
end
@enduml