@startuml purchase-order-attach-invoice
autonumber

actor "Procurement\nSpecialist" as a
participant Screen as f
participant Backend as b

a -> f : Click "Attach Invoice"
activate f
f -> f : Display Invoice Upload dialog
a -> f : Invoice
f -> b : Save Invoice
activate b
b -> b : Set payment as pending
return Invoice saved and\npayment pending
return Invoice saved and\npayment pending
@enduml