@startuml purchase-requisition-approve
autonumber

actor "Finance" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Click "Approve"
f -> b : Approve item
activate b
b -> b : Approve item
b -> b : Notify Procurement specialists
return Approve succeeds
f --> a : Approve succeeds
deactivate f
@enduml