@startuml purchase-order-attach-invoice
autonumber

actor "Procurement\nspecialist" as a
participant Screen as f
participant Backend as b

a -> f : Click "Attach invoice"
activate f
f --> f : Display Invoice Upload dialog
a -> f : Invoice
f -> b : Save Invoice and\nset payment as pending
activate b
return Invoice saved and\npayment pending
return Invoice saved and\npayment pending
@enduml