@startuml purchase-order-view
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant System as b

a -> f : Click "Purchase Orders"
activate f
f -> b : GetPurchaseOrders()
activate b
return PurchaseOrderDto[]
f --> a : PurchaseOrderDto[]
a -> f : Set search and filters
f -> b : GetPurchaseOrders(searchOpts)
activate b
return PurchaseOrderDto[]
f --> a : PurchaseOrderDto[]
a -> f : Select item
f -> b : GetPurchaseOrder(id)
activate b
return PurchaseOrderDto
return PurchaseOrderDto
@enduml