@startuml purchase-order-complete-payment
autonumber

actor "Finance" as a
participant UI as f
participant Backend as b

a -> f : Click "Complete payment"
activate f
f -> f : OpenCompletePaymentDialog()
a -> f : Receipt PDF
f -> b : CompletePurchasePayment(orderId, receiptFile)
activate b
return SuccessMessage
return SuccessMessage
@enduml