@startuml purchase-order-update
autonumber

actor "Purchase Specialist" as a
participant UI as f
participant System as b
participant Database as d

activate f

alt Update
    a -> f : Edit info and\nclick "PO Update Btn"
else Cancel
    a -> f : Click "PO Cancel Btn"
    f -> f : LoadDialog("Cancel")
    a -> f : Enter problem and\nclick "Cancel Ok Btn"
end

f -> b : UpdatePurchaseOrder\n(id, input)
activate b
b -> b : Validate(input)

alt validation succeeds
    b -> d : Update\n("PurchaseOrders", item)
    activate d
    return PurchaseOrder
    b -> b : Notify()
    b --> f : PurchaseOrderDto
    f --> a : PurchaseOrderDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
end
@enduml