@startuml report-generate
autonumber

actor "Director" as a
participant UI as f
participant System as b

a -> f : Click "Reports Nav Btn"
activate f
a -> f : Enter report type\nand time range then click\n"Report Generate Btn"
f -> b : GenerateReport\n(type, startMonth, endMonth)
activate b
return ReportDto
return ReportDto
@enduml