@startuml retailer-manage
autonumber

actor "Sales Manager" as a
participant UI as f
participant System as b

a -> f : Click "Retailers"
activate f
f -> b : GetRetailers()
activate b
return RetailerDto[]
f --> a : RetailerDto[]
a -> f : Set search and filters
f -> b : GetRetailers(SearchFilterOpts)
activate b
return RetailerDto[]
f --> a : RetailerDto[]

alt add
    a -> f : Click "Add"
    f -> f : OpenAddRetailerScreen()
    a -> f : Enter info and\nclick "Save"
    f -> b : AddRetailer(input)
    activate b
else update
    a -> f : Select item
    f -> b : GetRetailer(id)
    b --> f : RetailerDto
    f -> f : OpenUpdateRetailerScreen()
    a -> f : Enter info and\nclick "Save"
    f -> b : UpdateRetailer(id, input)
end

b -> b : Validate(create/input)

alt validation succeeds
    b --> f : RetailerDto
    f --> a : RetailerDto
else validation fails
    return ValidationFailure
    return ValidationFailure
end
@enduml