@startuml sales-retailer-manage
autonumber

actor "Sales\nmanager" as a
participant Screen as f
participant Backend as b

a -> f : Click "Retailers"
activate f
f -> b : Get items
activate b
return Items
f --> a : Items
a -> f : Set search and filters
f -> b : Search and filters
activate b
return Search and filter result
f --> a : Search and filter result

alt add
    a -> f : Click "Add"
    f -> f : Change screen
    a -> f : Enter data and\nClick "Save"
    f -> b : Add item
    activate b
else update
    a -> f : Select item
    f -> b : Get item
    b --> f : Item
    f -> f : Change screen
    f --> a : Item
    a -> f : Enter data and\nClick "Save"
    f -> b : Update item
end

b -> b : Validate item

alt validation succeeds
    b --> f : New/Updated item
    f --> a : New/Updated item
else validation fails
    return Validation failures
    return Validation failures
end
@enduml