@startuml sales-order-update
autonumber

actor "Sales Specialist" as a
participant UI as f
participant System as b
participant Database as d

activate f

alt Update
    a -> f : Edit info and\nclick "SO Update Btn"
else Cancel
    a -> f : Click "SO Cancel Btn"
    f -> f : LoadDialog("Cancel")
    a -> f : Enter problem and\nclick "Cancel Ok Btn"
end

f -> b : UpdateSalesOrder\n(id, input)
activate b
b -> b : Validate(input)

alt validation succeeds
    b -> d : Update\n("SalesOrders", item)
    activate d
    return SalesOrder
    b -> b : Notify()
    b --> f : SalesOrderDto
    f --> a : SalesOrderDto
else validation fails
    return ValidationFailure
    f --> a : ValidationFailure
end
@enduml