@startuml sales-order-accept-payment
autonumber

actor "Finance" as a
participant UI as f
participant System as b
participant RetailerMailServer as c

a -> f : Click "Accept payment"
activate f
f -> f : OpenAcceptPaymentDialog()
a -> f : Payment amount
f -> b : AcceptSalesPayment(orderId, payAmount)
activate b
b -> b : SendReceipt()
b -> c : Receipt
b -> b : Notify()
return SuccessMsg
return SuccessMsg
@enduml