@startuml sales-order-view
autonumber

actor "Sales Specialist" as a
participant UI as f
participant System as b
participant Database as d

a -> f : Click "Sales Orders\nNav Btn"
activate f
f -> b : GetSalesOrders()
activate b
b -> d : GetMany\n("SalesOrders", query)
activate d
return SalesOrder[]
return SalesOrderDto[]
f --> a : SalesOrderDto[]
a -> f : Set search and filters
f -> b : GetSalesOrders\n(searchOpts)
activate b
return SalesOrderDto[]
f --> a : SalesOrderDto[]
a -> f : Select item
f -> f : LoadScreen\n("Sales Order Details")
f -> b : GetSalesOrder(id)
activate b
b -> d : Get\n("SalesOrders", id)
activate d
return SalesOrder
return SalesOrderDto
f --> a : SalesOrderDto
@enduml