@startuml sales-order-accept-payment
autonumber

actor "Finance" as a
participant UI as f
participant System as b
participant Database as d

a -> f : Click "SO Accept\nPayment Btn"
activate f
a -> f : Payment amount
f -> b : AcceptSalesPayment\n(orderId, payAmount)
activate b
b -> d : Update\n("SalesOrders", id, item)
activate d
return SalesOrder
b -> b : SendReceipt()
b -> b : Notify()
return SuccessMsg
return SuccessMsg
@enduml