@startuml sales-order-complete
autonumber

actor "Sales Specialist" as a
participant UI as f
participant System as b
participant RetailerMailServer as c

activate f

a -> f : Click "Complete"\nor "Return"

alt Complete order
    f -> b : CompleteSalesOrder(id)
    activate b
    b -> b : SendInvoice()
    b -> c : Invoice
    return : SuccessMsg
    f --> a : SuccessMsg
else Return order
    a -> f : Enter problem\nthen click "Return"
    f -> f : LoadReturnOrderDialog()
    f -> b : ReturnOrder(id, input)
    activate b
    return SuccessMsg
    f --> a : SuccessMsg
    deactivate f
end
@enduml