@startuml sales-order-complete
autonumber

actor "Sales Specialist" as a
participant UI as f
participant Backend as b

activate f
a -> f : Click "Complete"
f -> b : CompleteSalesOrder(id)
activate b
b -> b : SendInvoice()
return SuccessMessage
f --> a : SuccessMessage
deactivate f
@enduml