@startuml sales-order-complete
autonumber

actor "Sales Specialist" as a
participant UI as f
participant System as b
participant Database as d

activate f

a -> f : Click complete buttons

alt Clicked = "SO Complete Btn"
    f -> b : CompleteSalesOrder(id)
    activate b
    b -> d : Update\n("SalesOrders", id, item)
    activate d
    return SalesOrder
    b -> b : SendInvoice()
    return : SuccessMsg
    f --> a : SuccessMsg
else Clicked = "SO Return Btn"
    f -> f : LoadDialog("Return")
    a -> f : Enter problem and\nclick "Return Ok Btn"
    f -> b : ReturnSalesOrder\n(id, input)
    activate b
    b -> d : Update\n("SalesOrders", id, item)
    activate d
    return SalesOrder
    return SuccessMsg
    f --> a : SuccessMsg
end
@enduml