@startuml sales-generate-invoice
autonumber

actor "Sales\nspecialist" as a
participant Screen as f
participant Backend as b

a -> f : Click "Generate sales invoice"
activate f
f -> b : Generate sales invoice
activate b
return Report
return Report
@enduml