@startuml sales-order-cancel
autonumber

actor "Sales\nspecialist" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Click "Cancel"
f -> b : Cancel item
activate b
return Cancel succeeds
f --> a : Cancel succeeds
deactivate f
@enduml