@startuml supply-list-manage
autonumber

actor "Procurement\nmanager" as a
participant Screen as f
participant Backend as b

a -> f : Click "Supplies"
activate f
f -> b : Get items
activate b
return Items
f --> a : Screen with items
a -> f : Set search and filters
f -> b : Search and filter options
activate b
b -> b : Generate search\nand filter result
return Search and filter result
f --> a : Search and filter result

alt add
    a -> f : Click "Add"
    f --> a : Add screen
    a -> f : Enter data and\nClick "Save"
    f -> b : Add item
    activate b
else update
    a -> f : Select item
    f -> b : Get item
    b --> f : Item
    f --> a : Screen with item
    a -> f : Enter data and\nClick "Save"
    f -> b : Update item
end

b -> b : Validate item

alt validation succeeds
    b -> b : Add/Update item
    b --> f : New/Updated item
    f --> a : New/Updated item
else validation fails
    return Validation failures
    return Validation failures
end
@enduml