@startuml supply-manage
autonumber

actor "Purchase Manager" as a
participant UI as f
participant System as b

a -> f : Click "Supplies"
activate f
f -> b : GetSupplies()
activate b
return SupplyDto[]
f --> a : SupplyDto[]
a -> f : Set search and filters
f -> b : GetSupplies(searchOpts)
activate b
return SupplyDto[]
f --> a : SupplyDto[]

alt add
    a -> f : Click "Add"
    f -> f : OpenAddSupplyScreen()
    a -> f : Enter info and\nclick "Save"
    f -> b : AddSupply(createDto)
    activate b
else update
    a -> f : Select item
    f -> b : GetSupply(id)
    b --> f : SupplyDto
    f -> f : OpenUpdateSupplyScreen()
    a -> f : Enter info and\nclick "Save"
    f -> b : UpdateSupply(id, updateDto)
end

b -> b : Validate(create/updateDto)

alt validation succeeds
    b --> f : SupplyDto
    f --> a : SupplyDto
else validation fails
    return ValidationFailure
    return ValidationFailure
end
@enduml