@startuml user-deactivate
autonumber

actor "Admin" as a
participant Screen as f
participant Backend as b

activate f
a -> f : Click "Deactivate"
f -> b : Deactivate user
activate b
return Deactivation succeeds
f --> a : Deactivation succeeds
deactivate f
@enduml