@startuml production-workflow

|prod_planner|Production Planner
|prod_manager|Production Manager
|inv_spec|Inventory Specialist

|prod_planner|
start
:Create Production Order;

|prod_manager|
if (Approved?) then (no)
    :Report problems;
    stop
else (yes)
endif

|inv_spec|
:Issue supplies;

|prod_planner|
:Update production progress;

if (Canceled?) then (yes)
    :Report problems;
    stop
else (no)
endif

|inv_spec|
:Check produced products;

if (Problems found?) then (yes)
    :Report problems\nand return order;
    stop
else (no)
endif

|inv_spec|
:Receive products\nand complete order;

stop
@enduml