@startuml production-order

[*] --> PendingApproval : Creates

state approval <<choice>>
PendingApproval --> approval
PendingApproval --> Canceled : Cancels

approval --> Rejected : Rejects
Rejected --> [*]
approval --> Approved : Approves

Approved --> Canceled : Cancels
Approved --> Producing : Issues supplies

Producing --> Canceled : Cancels
Producing --> Produced : Updates progress as "Produced"

state check <<choice>>
Produced --> check
check --> Completed : Receives products
Completed --> [*]
check --> Returned : Rejects due to problems
Returned --> [*]

Canceled --> [*]
@enduml