@startuml purchase-order

[*] --> Processing : Creates
Processing --> Canceled : Cancels
Processing --> Delivering : Updates progress as "Delivering"
Delivering --> Delivered : Updates progress as "Delivered"
Delivering --> Canceled : Cancels

state check <<choice>>
Delivered --> check
check --> Completed : Receives supplies
check --> Returned : Returns due to problems
Returned --> [*]

Completed --> PaymentDue : Attaches invoice\nfrom vendor
PaymentDue --> PaymentCompleted : Completes all due\namount to vendor
PaymentCompleted --> [*]

Canceled --> [*]
@enduml