@startuml purchase-requisition

[*] --> PendingApproval
PendingApproval --> Canceled : Cancels

state approval <<choice>>
PendingApproval --> approval
approval --> Rejected : Rejects
Rejected --> [*]
approval --> Approved : Approves

Approved --> Purchasing : Creates Purchase Order
Purchasing --> Delayed : Cancels or returns\nPurchase Order
Purchasing --> Completed : Completes Purchase Order
Completed --> [*]
Delayed --> Purchasing : Creates Purchase Order
Delayed --> Canceled : Cancels

Canceled --> [*]
@enduml