@startuml sales-order

[*] --> Processing : Creates
Processing --> Canceled : Cancels
Processing --> Delivering : Issue products
Delivering --> Delivered : Updates progress as "Delivered"
Delivering --> Canceled : Cancels

state check <<choice>>
Delivered --> check
check --> PaymentDue : Completes
check --> Returned : Returns due to problems
Returned --> [*]

PaymentDue --> PaymentCompleted : Accepts all due\namount from retailer
PaymentCompleted --> [*]

Canceled --> [*]
@enduml