@startuml admin
left to right direction

:Admin: as ad
:User: as u
u <|-- ad

rectangle System {
    u -- (Login)
    u -- (Logout)
    u -- (View my notifications)

    ad -- (Manage users)
}
@enduml