@startuml Admin
left to right direction

:Admin: as ad
:User: as u
u <|-- ad

rectangle System {
    u -- (Login)
    u -- (Logout)
    u -- (View my notifications)
    u -- (Manage my account)

    ad -- (Manage users)
    (Manage users) <|-- (Deactivate user)
}
@enduml