@startuml inventory
left to right direction

:Director: as d

:Inventory Manager: as im
:Inventory Specialist: as is
is <|-- im

rectangle Inventory {
    is -- (Manage stock)
    (Manage stock) <|.. (Import stock) : <<extends>>

    is -- (Supplies receive)
    (Supplies receive) ..> (View Purchase Order) : <<includes>>
    is -- (Products receive)
    (Products receive) ..> (View Production Order) : <<includes>>

    is -- (Supplies issue)
    (Supplies issue) ..> (View Production Order) : <<includes>>
    is -- (Products issue)
    (Products issue) ..> (View Sales Order) : <<includes>>

    im -- (Manage Warehouses)
    (Manage Warehouses) <|.. (Import Warehouses) : <<extends>>
    im -- (Generate Inventory Report)
    d -- (Generate Inventory Report)
}
@enduml