@startuml Inventory and Sales
left to right direction

:Director: as d

:Inventory manager: as im
:Inventory specialist: as is
is <|-- im

:Sales specialist: as s
:Sales manager: as sm
s <|-- sm

:Logistics specialist: as ls

rectangle System {
    s -- (Create Sales Order)
    s -- (View Sales Order)
    (View Sales Order) <|-- (Update Sales Order)
    (View Sales Order) <|-- (Update Sales Order status)
    (View Sales Order) <|-- (Cancel Sales Order)
    ls -- (Update Sales Order status)
    (View Sales Order) <|-- (Complete Sales Order)
    (View Sales Order) <|-- (Confirm Payment and Generate Receipt)

    sm -- (Generate Sales Report)
    d -- (Generate Sales Report)
    sm -- (Manage product list)
    sm -- (Manage retailer list)

    is -- (Manage stock)
    is -- (Warehouse issue)
    (Warehouse issue) --> (View Sales Order)

    im -- (Manage warehouse list)
    im -- (Generate Inventory Report)
    d -- (Generate Inventory Report)
}
@enduml