@startuml misc

:Admin: as ad
:User: as u
u <|-- ad

:Director: as d
:Purchase Manager: as pur_m
:Production Manager: as prod_m
:Inventory Manager: as im
:Sales Manager: as sm

rectangle Miscellaneous {
    u -- (Login)
    u -- (Logout)
    u -- (View my notifications)

    ad -- (Manage users)
    ad -- (Manage Configuration)

    d -- (Generate Reports)
    pur_m -- (Generate Reports)
    prod_m -- (Generate Reports)
    im -- (Generate Reports)
    sm -- (Generate Reports)
}
@enduml