@startuml misc
left to right direction

:Admin: as ad
:User: as u
u <|-- ad

:Director: as d

rectangle Miscellaneous {
    u -- (Login)
    u -- (Logout)
    u -- (View my notifications)

    ad -- (Manage users)
    ad -- (Manage Configuration)

    d -- (Generate Reports)
}
@enduml