@startuml sample

left to right direction

scale 1000 width
scale 1000 height

actor "sales" as sales
actor "inventory manager" as im


rectangle Order {
  usecase "Manage order" as UC0
  usecase "Check and update order status" as UC10
  usecase "Create order" as UC1
  usecase "Check and update stock product" as UC4
  usecase "Check order" as UC5
  usecase "Stock out depend on order" as UC5
  }

sales -- UC0
sales -- UC10
sales -- UC1
im -- UC5
im -- UC4
@enduml