@startuml sample

left to right direction

scale 1000 width
scale 1000 height

actor "sales" as sales
actor "inventory manager" as im


rectangle Order {
  usecase "Manage Order" as UC0
  usecase "Check Order status" as UC1
  usecase "Update Order status" as UC2
  usecase "Create Order" as UC3
  usecase "Check stock product" as UC4
  usecase "Update stock product" as UC5
  usecase "Check Order" as UC6
  usecase "Stock out depend on Order" as UC7
  }

sales -- UC0
sales -- UC1
sales -- UC2
sales -- UC3
im -- UC4
im -- UC5
im -- UC6
im -- UC7
@enduml