@startuml Procurement
left to right direction

:Director: as d
:Accountant: as a

:Purchase requester: as pr
:Procurement manager: as pm
:Procurement specialist: as ps
ps <|-- pm

:Inventory specialist: as is

rectangle System {
    pr -- (Create Purchase Requisition)
    pr -- (View my Purchase Requisition)
    (View my Purchase Requisition) <|-- (Update my Purchase Requisition)
    (View my Purchase Requisition) <|-- (Cancel my Purchase Requisition)
    a -- (Approve Purchase Requisition)
    (Approve Purchase Requisition) --> (View Purchase Requisition)

    ps -- (Create Purchase Order)
    (Create Purchase Order) --> (View Purchase Requisition)
    ps -- (View Purchase Order)
    (View Purchase Order) <|-- (Update Purchase Order)
    (View Purchase Order) <|-- (Update Purchase Order status)
    (View Purchase Order) <|-- (Attach Invoice to Purchase Order)
    (View Purchase Order) <|-- (Complete Purchase Order)
    (View Purchase Order) <|-- (Cancel Purchase Order)

    is -- (Warehouse receive)
    (Warehouse receive) --> (View Purchase Order)

    pm -- (Manage vendor list)
    pm -- (Manage procurement item list)

    pm -- (Generate Procurement Report)
    d -- (Generate Procurement Report)
}
@enduml