@startuml procurement
left to right direction

:Director: as d
:Finance: as f

:Production Planner: as pp
:Production Manager: as prm
pp <|-- prm

:Procurement Manager: as pm
:Procurement Specialist: as ps
ps <|-- pm

rectangle Procurement {
    pp -- (Create Purchase Requisition)
    pp -- (View Purchase Requisition)
    (View Purchase Requisition) <|.. (Update Purchase Requisition) : <<extends>>
    (View Purchase Requisition) <|.. (Cancel Purchase Requisition) : <<extends>>
    f -- (Approve Purchase Requisition)
    prm -- (Approve Purchase Requisition)
    (Approve Purchase Requisition) ..> (View Purchase Requisition) : <<includes>>

    ps -- (Create Purchase Order)
    (Create Purchase Order) ..> (View Purchase Requisition) : <<includes>>
    ps -- (View Purchase Order)
    (View Purchase Order) <|.. (Update Purchase Order) : <<extends>>
    (View Purchase Order) <|.. (Update Purchase Order progress) : <<extends>>
    (View Purchase Order) <|.. (Attach Purchase Invoice) : <<extends>>
    (View Purchase Order) <|.. (Cancel Purchase Order) : <<extends>>
    f -- (Complete Purchase Order payment)
    (Complete Purchase Order payment) ..> (View Purchase Order) : <<includes>>

    pm -- (Manage Vendors)
    (Manage Vendors) <|.. (Import Vendors) : <<extends>>
    pm -- (Manage Supplies)
    (Manage Supplies) <|.. (Import Supplies) : <<extends>>
    pm -- (Generate Procurement Report)
    d -- (Generate Procurement Report)
}
@enduml