@startuml production
left to right direction

:Production Planner: as pp
:Production Manager: as pm
pp <|-- pm

rectangle Production {
  pp -- (View Production Order)
  pp -- (Create Production Order)
  (View Production Order) <|.. (Update Production Order) : <<extends>>
  (View Production Order) <|.. (Update progress\nof Production Order) : <<extends>>

  pm -- (Approve Production Order)
  (Approve Production Order) ..> (View Production Order) : <<includes>>

  pm -- (Manage Production\nFacilities)
  (Manage Production\nFacilities) <|.. (Import) : <<extends>>
}
@enduml