@startuml production
left to right direction

:Production Planner: as pp
:Production Manager: as pm
pp <|-- pm

:Director: as d

rectangle Production {
  pp -- (View Production Order)
  pp -- (Create Production Order)
  (View Production Order) <|.. (Update Production Order) : <<extends>>
  (View Production Order) <|.. (Update Production Order progress) : <<extends>>
  (View Production Order) <|.. (Complete Production Order) : <<extends>>
  (View Production Order) <|.. (Cancel Production Order) : <<extends>>

  pm -- (Approve Production Order)
  (Approve Production Order) ..> (View Production Order) : <<includes>>

  pm -- (Manage Manufacturing Facilities)
  (Manage Manufacturing Facilities) <|.. (Import Manufacturing Facilities) : <<extends>>
  pm -- (Generate Production Report)
  d -- (Generate Production Report)
}
@enduml