@startuml sample
left to right direction

:Production planner: as pp
:Production manager: as pm
pp <|-- pm

:Director: as d

rectangle Production {
  pp -- (View Production Order)
  pp -- (Create Production Order)
  (View Production Order) <|-- (Update Production Order)
  (View Production Order) <|-- (Update Production Order status)
  (View Production Order) <|-- (Complete Production Order)
  (View Production Order) <|-- (Cancel Production Order)

  pm -- (Manage Manufacturing Facility list)
  pm -- (Generate Production Report)
  d -- (Generate Production Report)
}
@enduml