@startuml Sales
left to right direction

:Director: as d

:Production Manager: as pm

:Sales Specialist: as s
:Sales Manager: as sm
s <|-- sm

:Logistics Specialist: as ls

rectangle Sales {
    s -- (Create Sales Order)
    s -- (View Sales Order)
    (View Sales Order) <|-- (Update Sales Order)
    (View Sales Order) <|-- (Update Sales Order status)
    (View Sales Order) <|-- (Cancel Sales Order)
    ls -- (Update Sales Order status)
    (View Sales Order) <|-- (Generate Sales Invoice)
    (View Sales Order) <|-- (Complete Sales Order)

    sm -- (Generate Sales Report)
    d -- (Generate Sales Report)
    pm -- (Manage Products)
    sm -- (Manage Products)
    sm -- (Manage Retailers)
}
@enduml